name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Rustodian v__VERSION__'
          releaseBody: |
            See the assets to download and install this version.
            
            ## What's Changed
            - Updated app icon from F to R
            - Fixed dependency compatibility issues
            - Improved build process
            
            ## Downloads
            - **Windows**: Download `Rustodian_1.2.0_x64_en-US.msi` or `Rustodian_1.2.0_x64-setup.exe`
            - **macOS**: Download `Rustodian_1.2.0_aarch64.dmg` (Apple Silicon) or `Rustodian_1.2.0_x64.dmg` (Intel)
            - **Linux**: Download `rustodian_1.2.0_amd64.AppImage` or `rustodian_1.2.0_amd64.deb`
          releaseDraft: true
          prerelease: false
